scenario:
  # name: warehouse_default
  name: bookstore_default

entities:
  turtlebot3:
    model: burger
    # start_pose:
    #   x: -3.5
    #   y: -9.0
    #   z: 0.0
    #   yaw: 0.0
    start_pose:
      x: -6.0
      y: 6.5
      z: 0.0
      yaw: 0.0
    # goal_pose:
    #   x: 30.0
    #   y: 50.0
    #   z: 0.0
    #   yaw: 0.0
    goal_pose:
      x: 7.0
      y: -6.3
      z: 0.0
      yaw: 0.0

simulation:
  use_sim_time: true
  # world: dynamic_logistics_warehouse
  world: aws_robomaker_bookstore_world